### ISSUE TITLE
Modules still show Palm-Up sign

### ISSUE THREAD

**Issue by inetbusiness** [DummkopfOfHachtenduden/Replace.Certification#1]
All Modules except MachineManager still show that Palm-up-sign
![image](https://github.com/DummkopfOfHachtenduden/Replace.Certification/assets/2929919/55a028e3-7bd8-4b38-a561-4f9077371bbe)

Can we fix that somehow?

**Comment by DummkopfOfHachtenduden** [comment]
This has nothing to do with the Certification. The Hand Icon is literally shown at the roll of a dice.
See `v6 = rand() % 2`
![image](https://github.com/DummkopfOfHachtenduden/Replace.Certification/assets/13951844/b0c2b30f-ce59-4b42-9cba-25c4d4eb7cac)

They probably intended to use this later on and put the random selection as a placeholder.
If you want to fix it purely for the looks then search for the `DrawIcon` function and check it's references. I won't provide this for everyone because it's really not essential.

**Comment by inetbusiness** [comment]
alright, thanks mate
